### ISSUE TITLE
check done err

### ISSUE THREAD

**Issue by X-WJ** [FlyPythons/DAGflow#1]
Hi:
Now ,I have test dagflow on arm platform.But  some err occurred.
while i hava a set of tasks in parallel. while all tasks in this paralleltask  were done and it should gegerate next DAG,but log 
file tells me that  the paralleltask were failed .And I check the task, they  were done and generaeted  done files. 
Can you tell me it is a bug on arm or i have some typo in my task ?

Hope your reply.

**Comment by FlyPythons** [comment]
I had not test it in arm. Could you provides the codes and error message?

**Comment by X-WJ** [comment]
Hi，it works fine. 
when i have a job on sge  with dagflow and it finished quickly,the bug occurs .
Now i have change these tasks running on local ,and it works well .
Thank you for your reply.
